[package]
name = "ureq"
version = "0.6.0"
authors = ["Martin Algesten <martin@algesten.se>"]
description = "Minimal HTTP request library"
license = "MIT/Apache-2.0"
repository = "https://github.com/algesten/ureq"
readme = "README.md"
keywords = ["web", "request", "http", "rest", "client"]
categories = ["web-programming::http-client"]

[features]
default = ["tls"]
json = ["serde_json"]
charset = ["encoding"]
tls = ["native-tls"]

[dependencies]
ascii = "0.9"
base64 = "0.9"
chunked_transfer = "0.3"
cookie = { version = "0.11", features = ["percent-encode"] }
lazy_static = "1"
qstring = "0.6"
url = "1.6"
native-tls = { version = "0.2", optional = true }
serde_json = { version = "1", optional = true }
encoding = { version = "0.2", optional = true }
