[package]
name = "ureq"
version = "0.8.0"
authors = ["Martin Algesten <martin@algesten.se>"]
description = "Minimal HTTP request library"
license = "MIT/Apache-2.0"
repository = "https://github.com/algesten/ureq"
readme = "README.md"
keywords = ["web", "request", "http", "rest", "client"]
categories = ["web-programming::http-client"]
edition = "2018"

[features]
default = ["tls"]
json = ["serde_json"]
charset = ["encoding"]
tls = ["rustls", "webpki", "webpki-roots"]

[dependencies]
ascii = "0.9"
base64 = "0.10"
chunked_transfer = "0.3"
cookie = { version = "0.11", features = ["percent-encode"] }
lazy_static = "1"
qstring = "0.6"
url = "1"
rustls = { version = "0.13", optional = true, features = [] }
webpki = { version = "0.18", optional = true }
webpki-roots = { version = "0.15", optional = true }
serde_json = { version = "1", optional = true }
encoding = { version = "0.2", optional = true }
