[package]
name = "ureq"
version = "0.1.0"
authors = ["Martin Algesten <martin@algesten.se>"]
description = "Minimal HTTP request library"
license = "MIT/Apache-2.0"
repository = "https://github.com/algesten/ureq"
readme = "README.md"
keywords = ["web", "request", "http", "rest", "client"]
categories = ["web-programming::http-client"]

[dependencies]
ascii = "0.9"
base64 = "0.9"
chunked_transfer = "0.3"
cookie = { version = "0.10", features = ["percent-encode"] }
dns-lookup = "0.9.1"
encoding = "0.2"
lazy_static = "1"
qstring = "0.6"
native-tls = "0.1"
serde_json = "1"
url = "1.6"
